### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by Wolf-Heart** [PavelBlend/stalker_thm_editor#1]
Что это и для чего приблизительно догадываюсь, но не понял как это работает и какой функционал.
Хотелось бы хоть какое-то описание, инструкцию.

**Comment by PavelBlend** [comment]
Это недоделанная программка. Хотел сделать thm редактор, чтобы без СДК редактировать и смотреть параметры текстурок, объектов, звуков, групп. Но даже это не была основной целью. Основная цель (для меня) понять, как устроен формат thm, а редактор thm - это как бы побочный эффект от разбора этого формата. Я пока забросил разработку этой программы. А вообще, я ещё хотел как-то эти thm внедрить в блендер (может внутри блендера можно было бы менять превьюхи для текстур и объектов), и хотел полностью понять этот формат, и придумать, что ещё можно менять в этих thm с помощью блендера. Может быть сделал бы какие-то аддоны или отдельные скрипты, которые бы могли как-то модифицировать эти thm'ки.

Я давно делал даже интерфейс, но не залил его в репозиторий:
![011](https://user-images.githubusercontent.com/7983249/76159172-aef67a00-612e-11ea-93d1-5a5ffd4e76b5.jpg)

**Comment by Wolf-Heart** [comment]
Не знаю поможет тебе это или нет, но есть програмка AXRToolset: 
https://github.com/revolucas/AXRToolset
В ней реализован просмотр и редактор THM:
[url=https://postimg.cc/tsGsgLYC][img]https://i.postimg.cc/tsGsgLYC/1.png[/img][/url]
[url=https://postimg.cc/XXF3vXFd][img]https://i.postimg.cc/XXF3vXFd/2.png[/img][/url]

**Comment by Wolf-Heart** [comment]
> 
> 
> Не знаю поможет тебе это или нет, но есть програмка AXRToolset:
> https://github.com/revolucas/AXRToolset
> В ней реализован просмотр и редактор THM:
> https://i.postimg.cc/HkVX6mm5/1.png
> https://i.postimg.cc/MZ3GdQpP/2.png
